### ISSUE TITLE
what is the minimum requirements to run in local?

### ISSUE THREAD

**Issue by Amrosx** [meta-llama/llama-stack-apps#86]
``` self.weight = Parameter(torch.Tensor(self.output_size_per_partition, self.in_features))
  torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 7.69 GiB of which 13.94 MiB is free. Including non-PyTorch memory, this process has 7.64 GiB memory in use. Of the allocated memory 7.34 GiB is allocated by PyTorch, and 121.77 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. ```

**Comment by ashwinb** [comment]
@Amrosx  What kind of GPU do you have? What model are you trying to use?

**Comment by Amrosx** [comment]
@ashwinb I am using NVIDIA RTX A5000 24G
the models
Llama3.1-8b-instruct
Llama-Guard-3-8B
same as in the README

**Comment by ashwinb** [comment]
What command are you using to start? I think you need to disable safety (i.e., avoid loading the Llama-Guard-3-8B model or maybe use the much lighter weight Llama-Guard-3-1B we just released) to be able to fit everything onto your card.

**Comment by Amrosx** [comment]
I have followed the instruction of llama stack build , configuration and run 8b-instruct
I run with safety and without but nothing change
 python app/main.py --disabled-safety but no change
python app/main.py
when I sent Hello message 
I got this error CUDA out of memory in server side

**Comment by yanxi0830** [comment]
You may start with `Llama3.2-1B-Instruct` model for inference. E.g. 

```yaml
inference: 
  - provider_id: meta-reference
    provider_type: meta-reference
    config:
      model: Llama3.2-1B-Instruct
      quantization: null
      torch_seed: null
      max_seq_len: 4096
      max_batch_size: 1
```
